name: Java CI with Gradle

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Start SUT
        run: java -jar ./artifacts/app-replan-delivery.jar &

      - name: Wait for SUT to be ready
        run: sleep 10

      - name: Run tests with Gradle
        run: ./gradlew test --info -Dselenide.headless=true

      - name: Stop SUT
        if: always()
        run: |
          PID=$(lsof -ti:9999)
          if [ -n "$PID" ]; then
            kill -9 $PID
          fi
